import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { loadConfig, ROOT } from '../server/config.js';
import { Store } from '../server/store.js';
import { addDocument } from '../server/service.js';
import { RoleClient } from '../server/provider.js';
import { Orchestrator } from '../server/orchestrator.js';
import { testProvider } from '../test-support/provider.js';
import { buildDiff } from '../server/diff.js';
import { contextBlocks } from '../server/extract.js';
import { coverage } from '../server/coverage.js';
import { exportHtml } from '../server/export.js';
const names=await fs.readdir(ROOT),before=names.find(n=>/редакция_8.*\.docx$/i.test(n)),after=names.find(n=>/редакция_9.*\.docx$/i.test(n));
assert.ok(before&&after,'Контрольные DOCX №8 и №9 не найдены.');
const dataDir=path.join(ROOT,'test-results',`control-${Date.now()}`),config=loadConfig({dataDir,testMode:true}),store=new Store(dataDir);await store.init();const run=await store.create(config,{mode:'test',explicit_pair:true,name:'Контроль №8 → №9 · тестовый provider'});
const a=await addDocument(store,run,{name:before,side:'A',buffer:await fs.readFile(path.join(ROOT,before))}),b=await addDocument(store,run,{name:after,side:'B',buffer:await fs.readFile(path.join(ROOT,after))});
const point=(d,n)=>d.blocks.find(b=>b.text.trim().startsWith(n+'. '));
assert.match(point(a,'9.15').text,/осуществляется/);assert.match(point(b,'9.15').text,/может осуществляться/);
assert.match(point(a,'9.37').text,/Директору направления внутреннего аудита/);assert.match(point(b,'9.37').text,/Директору операционного аудита/);
assert.match(point(b,'4.4').text,/независимости и объективности/);assert.match(point(b,'4.4').text,/раскрытие информации/);
assert.match(point(a,'5.4.4').text,/взаимодействует с субъектами СВК/);assert.match(point(b,'5.3.3').text,/взаимодействуют с субъектами СВК/);
assert.match(point(a,'5.6.2').text,/формировать группы контроля качества/);
assert.match(point(a,'5.9').text,/не имеют права/);assert.match(point(b,'5.8').text,/не имеют права/);
assert.notDeepEqual(a.blocks.slice(point(a,'3.4').order+1,point(a,'3.4').order+5).map(b=>b.text),b.blocks.slice(point(b,'3.4').order+1,point(b,'3.4').order+5).map(b=>b.text));
for(const [oldNo,newNo]of [['5.9.3','5.8.3'],['5.10.3','5.9.3'],['5.11.4','5.10.4']])assert.equal(point(a,oldNo).text.replace(/^\s*\d+(?:\.\d+)+\.\s*/,''),point(b,newNo).text.replace(/^\s*\d+(?:\.\d+)+\.\s*/,''));
assert.ok(contextBlocks(b,point(b,'5.8.3')).some(p=>p.text.includes('не имеют права')));
const diff=buildDiff(run,a.blocks,b.blocks),row=diff.rows.find(r=>r.before_refs.some(r=>r.block_id===point(a,'9.15').id));assert.ok(row.word_diff.some(p=>p.kind==='added'&&p.text.includes('может')));
const client=new RoleClient(store,config,{testProvider}),orchestrator=new Orchestrator(store,client,config);await orchestrator.start(run);await orchestrator.wait(run);assert.equal(run.last_error,null,JSON.stringify(run.last_error));assert.ok(run.report);assert.ok(run.tasks.every(t=>!t.current||t.status==='done'));assert.equal(coverage(run).counts.unchecked,0);
await fs.writeFile(path.join(dataDir,'control-report.html'),exportHtml(run),'utf8');const summary={mode:'TEST PROVIDER — NO LIVE QUALITY ASSESSMENT',state:run.state,documents:[a,b].map(d=>({name:d.name,sha256:d.file_hash,blocks:d.blocks.length,status:d.status})),calls:run.budgets.llm_calls,tasks:run.tasks.filter(t=>t.current).length,coverage:coverage(run).counts,export:path.join(dataDir,'control-report.html')};await fs.writeFile(path.join(dataDir,'summary.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
