import { registry } from './registry.js';
import { resolveRef } from './validate.js';
import { labels } from '../shared/contracts.js';
import { escapeHtml as e, refKey } from './util.js';
export function coordinate(block) {
  const c=block.coordinates,parts=[];
  if(block.numbering?.label)parts.push(`пункт ${block.numbering.label}`);
  const number=/^\s*(\d+(?:\.\d+)+)\./.exec(block.text);if(number)parts.push(`пункт ${number[1]}`);
  if(c.page)parts.push(`страница ${c.page}`);if(c.sheet)parts.push(`лист «${c.sheet}»`);if(c.table)parts.push(`таблица ${c.table}`);if(c.row)parts.push(`строка ${c.row}`);if(c.column)parts.push(`ячейка ${c.column}`);if(c.paragraph)parts.push(`абзац ${c.paragraph}`);if(c.part&&c.part!=='body')parts.push(c.part);return parts.join(', ')||`блок ${block.order+1}`;
}
export function exportHtml(run) {
  const reg=registry(run),report=run.report,sources=[...new Map([...reg.findings.flatMap(f=>[...f.before_refs,...f.after_refs]),...reg.functions.flatMap(f=>f.source_refs),...reg.org_units.flatMap(o=>o.source_refs),...reg.function_links.flatMap(l=>l.evidence_refs),...reg.org_links.flatMap(l=>l.evidence_refs),...(run.plan?.groups||[]).flatMap(g=>g.evidence_refs)].map(r=>[refKey(r),r])).values()],sourceIndex=new Map(sources.map((r,i)=>[refKey(r),i+1]));
  const refs=rs=>rs.map(r=>`<a href="#source-${sourceIndex.get(refKey(r))}">[${sourceIndex.get(refKey(r))}]</a>`).join(' ');
  const bullet=items=>`<ul>${items.map(t=>`<li>${e(t)}</li>`).join('')}</ul>`;
  const functionName=id=>{const f=reg.functions.find(f=>f.id===id);return f?`${f.responsible.value||'Ответственный не установлен'}: ${f.action.value||'Действие не установлено'} ${f.object.value||''}`:'Функция недоступна';};
  const linksHtml=`<h2>Соответствие функций и ответственности</h2><table><tr><th>До</th><th>После</th><th>Изменение</th><th>Основания</th></tr>${reg.function_links.map(l=>`<tr><td>${e(l.before_ids.map(functionName).join('; '))}</td><td>${e(l.after_ids.map(functionName).join('; '))}</td><td>${e(l.relation)} ${e(l.uncertainty.join('; '))}</td><td>${refs(l.evidence_refs)}</td></tr>`).join('')}</table><h2>Реестр функций</h2><table><tr><th>Сторона / ответственный</th><th>Функция</th><th>Область, обязательность, условия</th><th>Источники</th></tr>${reg.functions.map(f=>`<tr><td>${f.side==='A'?'До':'После'} · ${e(f.responsible.value||'Не установлен')}</td><td>${e(f.action.value||'Не установлено')} ${e(f.object.value||'')}</td><td>${e(['scope','modality','conditions','deadlines','exceptions'].map(k=>f[k].value).filter(Boolean).join('; '))}${bullet(f.uncertainty)}</td><td>${refs(f.source_refs)}</td></tr>`).join('')}</table>`;
  return `<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Hectra — заключение</title><style>body{font:16px/1.55 system-ui;max-width:1100px;margin:40px auto;padding:20px;color:#222}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccc;padding:10px;text-align:left;vertical-align:top}blockquote{white-space:pre-wrap;border-left:3px solid #888;padding-left:16px}.notice{padding:16px;background:#fff1d6}article{border-top:1px solid #bbb;padding:18px 0}@media print{a{color:inherit}}</style>
  <h1>Hectra · Анализ организационных изменений</h1><p>${e(run.name)} · ${e(new Date().toISOString())} · Версия реестра ${reg.version} · Версия заключения ${report?.version||'—'}</p><p>Состояние: ${e(labels.states[run.state]||run.state)}${report?.stale?' · Заключение устарело после изменения реестра':''}</p>
  ${run.mode==='test'?'<p class="notice">ТЕСТОВЫЙ ПРОГОН. Синтетические ответы проверяют программный маршрут. Это не результат LLM-анализа.</p>':''}
  <h2>Общий вывод</h2>${!report||report.state==='structured_fallback'?'<p class="notice">Текстовое заключение не собрано. Ниже сохранённый структурированный реестр.</p>':''}${reg.coverage.counts.unchecked?`<p class="notice">Неполная проверка: ${reg.coverage.counts.unchecked} доступных блоков не проверены judge.</p>`:''}
  ${(report?.overview||[]).map(c=>`<p>${e(c.text)} ${c.finding_refs.map(fid=>`<a href="#${e(fid)}">Находка</a>`).join(' ')}</p>`).join('')}
  <h2>Состав комплектов</h2><table><tr><th>Сторона</th><th>Документ</th><th>Извлечение</th></tr>${run.documents.map(d=>`<tr><td>${d.side==='A'?'А · До':'Б · После'}</td><td>${e(d.name)}<br>Версия извлечения ${d.extraction_version}</td><td>${e(d.status)}${bullet(d.warnings)}</td></tr>`).join('')}</table>
  <h2>Карта изменений</h2><table><tr><th>Группа</th><th>До</th><th>После</th><th>Основание</th></tr>${(run.plan?.groups||[]).map(g=>`<tr><td>${e(g.label)} · ${e(g.relation)}</td><td>${e(g.before.map(r=>run.documents.find(d=>d.id===r.document_id)?.name).join('; '))}</td><td>${e(g.after.map(r=>run.documents.find(d=>d.id===r.document_id)?.name).join('; '))}</td><td>${e(g.rationale)} ${e(g.uncertainty.join('; '))}</td></tr>`).join('')}</table>
  ${linksHtml}<h2>Находки и действия</h2>${reg.findings.map(f=>`<article id="${e(f.id)}"><h3>${e(labels.categories[f.category])}: ${e(f.claim)}</h3><p>${e(f.explanation)}</p><p>До: ${refs(f.before_refs)} · После: ${refs(f.after_refs)}</p><p>Judge: ${e(labels.verdicts[f.judge_status])} · Решение человека: ${e(f.human_status)} · Версия ${f.version}</p><p>Значимость: ${e(f.significance)}. ${e(f.significance_basis)}</p><p>Действие: ${e(f.action)}</p>${bullet([...f.uncertainty,...f.limitations])}${bullet(run.reviews.filter(r=>r.finding_id===f.id).map(r=>`${r.author}: ${r.text||r.decision}`))}</article>`).join('')||'<p>Находок в текущем реестре нет. Это не подтверждает отсутствие проблем.</p>'}
  <h2>Вопросы для проверки</h2>${bullet((report?.questions||[]).map(c=>c.text))}<h2>Рекомендации</h2>${bullet((report?.recommendations||[]).map(c=>c.text))}
  <h2>Основания и полнота</h2><table>${Object.entries(reg.coverage.counts).map(([k,v])=>`<tr><th>${e(labels.coverage[k]||k)}</th><td>${v}</td></tr>`).join('')}</table>${bullet([...new Set([...reg.limitations,...(report?.limitations||[])])])}
  <h2>Исходные цитаты</h2>${sources.map((ref,i)=>{const b=resolveRef(run,ref),d=run.documents.find(d=>d.id===ref.document_id);return `<article id="source-${i+1}"><h3>[${i+1}] ${e(d.name)}</h3><p>${d.side==='A'?'До':'После'} · ${e(coordinate(b))} · Версия извлечения ${ref.extraction_version}</p><blockquote>${e(b.text)}</blockquote>${[...b.context.heading_ids,...b.context.parent_ids,b.context.intro_id].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).map(bid=>`<blockquote>Контекст: ${e(d.blocks.find(x=>x.id===bid)?.text)}</blockquote>`).join('')}</article>`;}).join('')}
  </html>`;
}
